{% set name = "spec-classes" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/58/60/aba0e815c174a2da7d3f0e989140fdf9dbbe297ff38c4c56d51e00bdeb7e/spec_classes-{{ version }}.tar.gz
  sha256: ae4a0a4111dd5318ce032dc75c1e605e187a8c5ae92a255e22f56833a83f7c4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
