{% set name = "spec-classes" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4b/de/a0e3199d7af24e4cf481d47e8051aa26ade6ed084a6b9d0c7a2989d27d01/spec_classes-1.5.1.tar.gz
  sha256: 3e9fa57e9e11c94196d64a34b194d3c463e7499a75a888f9d55012403aa9e5d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.2
    - setupmeta >=2.7.11
    - hatch
    - hatch-vcs
  run:
    - python >=3.7
    - cached-property >=1.5.2
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
