{% set name = "spec-classes" %}
{% set version = "1.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/2f/7c/eff344d39c3c36cdd19d5d16d45beb2976d185851f58c14c70a8f36f6374/spec_classes-1.5.9.tar.gz
  sha256: 1aca191537bb39c7d595a68488e2469bb8978ea4fb64d348c933a0d6249eb67a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - cached-property >=1.5.2
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
