{% set name = "spec-classes" %}
{% set version = "1.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/a2/5d/e64dd653a45fcfbfe2eee7e6f095faf9ee7a5d562be896679cfdbd3e5261/spec_classes-{{ version }}.tar.gz
  sha256: 2ee1d09874f5ae103e4b8d821ddb18114dc27d7b93146428314168d8f5982e3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
