{% set name = "spec-classes" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/22/ac/0960b5e5978ca486152e3597f6c93ace9227cd65fcca61901e7d9f45c8dc/spec_classes-1.4.0.tar.gz
  sha256: 5ab635f7f96e5f6bda43066d306f47ce6618db8763a52ccb4bc499c2c4405900

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.2
    - setupmeta >=2.7.11
    - hatch
    - hatch-vcs
  run:
    - python >=3.7
    - cached-property >=1.5.2
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
