{% set name = "spec-classes" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/57/75/98889bf4c16f8211777f0be8cea4dc8412a6fd7a809fff9821059a64b906/spec_classes-1.5.5.tar.gz
  sha256: 9de3d90951cfadec5892f3f129c77297a4194f9773c37ec91c4bd7bf2b7f5c19

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setupmeta >=2.7.11
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - cached-property >=1.5.2
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
