{% set name = "spec-classes" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/ff/54/bf4134c6f2848118c1b6cb75c6027e6aff58246bd8ddd52bc9fcac6e3063/spec_classes-{{ version }}.tar.gz
  sha256: de745ff093520948c63397e1fc1800c240435389f4a2e40471075262591faf06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - inflect >=5.0.0
    - lazy-object-proxy >=1.5.0
    - typing_extensions >=4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - spec_classes

about:
  home: https://github.com/matthewwardrop/spec-classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple way to incrementally build type-checked specifications.
  description: |
    This package allows you to turn classes into specifications with
    type-checked attributes and utility methods for incrementally building the
    specification.
  doc_url: https://github.com/matthewwardrop/spec-classes
  dev_url: https://github.com/matthewwardrop/spec-classes

extra:
  recipe-maintainers:
    - matthewwardrop
